<template>
  <div class="loading">
    <div class="loadingio-spinner-spinner-nt8qsiqmnys">
      <div class="ldio-aedhki2hmz7">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<script>
export default {};
</script>
<style type="text/css">
.loading {
  position: fixed;
  width: 100%;
  height: 100%;
  z-index: 10000;
  background: rgba(118, 76, 41, 0.2);
}
@keyframes ldio-aedhki2hmz7 {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-aedhki2hmz7 div {
  left: 50%;
  top: 50%;
  position: absolute;
  animation: ldio-aedhki2hmz7 linear 0.5988023952095808s infinite;
  background: #00bcd4;
  width: 18px;
  height: 24px;
  border-radius: 9px / 12px;
  transform-origin: 9px 52px;
}
.ldio-aedhki2hmz7 div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.5489021956087824s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.49900199600798395s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.44910179640718556s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.39920159680638717s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.3493013972055888s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.2994011976047904s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.24950099800399198s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.19960079840319359s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.1497005988023952s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.09980039920159679s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.049900199600798396s;
  background: #00bcd4;
}
.ldio-aedhki2hmz7 div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #00bcd4;
}
.loadingio-spinner-spinner-nt8qsiqmnys {
  position: absolute;
  top: 40%;
  left: 45%;
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-aedhki2hmz7 {
  width: 50%;
  height: 50%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-aedhki2hmz7 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
